/**
 * generated by Xtext 2.31.0
 */
package org.example.domainmodel.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getDatatype()
 * @model
 * @generated
 */
public interface Datatype extends Type
{
} // Datatype
